// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiPrueba.Context;

namespace apiPrueba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210514090706_PrimerCommitBBDD")]
    partial class PrimerCommitBBDD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apiPrueba.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ArtistId")
                        .HasColumnName("artist_id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("apiPrueba.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<string>("Genre")
                        .HasColumnName("genre_molon");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("apiPrueba.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Codigo");

                    b.Property<int>("EjercicioContable");

                    b.Property<double>("Importe");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("apiPrueba.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AlbumId")
                        .HasColumnName("album_id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(10);

                    b.Property<DateTime>("PublishDate")
                        .HasColumnName("publish_date");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("apiPrueba.Models.Album", b =>
                {
                    b.HasOne("apiPrueba.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("apiPrueba.Models.Song", b =>
                {
                    b.HasOne("apiPrueba.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
